apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - name: rest-api
    port: 9200
    protocal: TCP
    targetPort: 9200
  - name: node-communication
    port: 9300
    protocal: TCP
    targetPort: 9300
  selector:
    name: elascticsearch
  sessionAffinity: None
  type: ClusterIP
