kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: prometheus
    chart: prometheus-9.5.2
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: prometheus
data:
  alertmanager.yml: |
    global:
    receivers:
      - name: default-receiver
      - name: webhook
        webhook_configs:
          - url: "http://prom-webhook.prometheus.svc.cluster.local/line"
    route:
      #  How long to wait to buffer alerts of the same group before sending initially.
      group_wait: 5s
      #  How long to wait before sending an alert that has been added to a group which contains already fired alerts.
      group_interval: 5s
      receiver: default-receiver
      #  How long to wait before re-sending a given alert that has already been sent.
      repeat_interval: 5s

      routes:
        - receiver: webhook
          match:
            app: app_server
