apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: echo-server
  name: echo-server
  namespace: myproject
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: echo-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - image: hashicorp/http-echo
        imagePullPolicy: IfNotPresent
        name: echo-server
        args: ["-listen=:8080", "-text=\"hello world\""]
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
