apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: myproject
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: echo-server
  sessionAffinity: None
  type: ClusterIP
